  on: [push, pull_request]
  jobs:
    build:
      runs-on: macos-latest
      strategy:
        matrix:
          python-version: [3.6]

      steps:
        - uses: actions/checkout@v2
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
        - name: Install package dependencies
          run:  |
           python -m pip install --upgrade pip
           if [ -f requirements.text ]; then pip install -r requirements.txt; fi

        - name: Test package install
          run: pip install .

        - name: Test that example is autosaved
          run:  |
           if [ -f example.streambook.py ]; then rm example.streambook.py;fi
           python -m streambook example.py && cat example.streambook.py | head


